Change the default permissions of the TLKM chardevs to 0666
esa-tu-darmstadt/tapasco pull request #229
Opened 2020-07-09 08:50 UTC by jahofmann

This commit changes the default permissions of the TaPaSCo chardev to 0666, which means everyone can access it by default.

There are some pros and cons to this, which is why I marked this pull request as "Discussion".

For most users this should be more convenient, however, this is not really the Linux way to do things. In the Linux kernel there is the  saying: 'Policy belongs in user space, not in the kernel.'.

Accordingly, the proper way to do this is e.g. to use udev (and there should be a corresponding udev rule somewhere) which should be installed automatically in the release packages.

Hence, this is more a convenience feature for developers than anything else.

What do you think?

2020-09-23 13:06 UTC, cahz requested changes
Please fix the line indentation

2020-09-23 13:08 UTC, jahofmann commented
The commit wasn't final, it's more about the discussion if this is "good" behavior or not.

2020-09-23 13:16 UTC, jojowi commented
When you (re)load TLKM it automatically sets the permission for the current user correctly, right?
So this would only be useful when someone else (who did not load the TLKM) wants to use the chardevs?

2020-09-23 13:18 UTC, jahofmann commented
Nope, TLKM does not set any permissions. The default is simply root:root with strict permissions, as is the default for all linux drivers. A user can not load any kernel modules, only root can do that.

2020-09-24 12:04 UTC, jojowi commented
You're right, setting the permissions for the current user (by making him the owner) happens only in the bit-reload.sh script.
But I'm still not sure we actually need this. Not that I would have a problem with it but at least from my point it's not necessary

2020-10-13 10:01 UTC, jahofmann commented
Will close this for now as it is not required and against the kernel rules.

2020-10-13 10:01 UTC, closed without merging