Add support for Vivado 2020.2
esa-tu-darmstadt/tapasco pull request #275
Opened 2021-04-06 11:56 UTC by cahz

2021-04-09 07:35 UTC, sommerlukas commented
This PR also includes support for `vitis_hls`. The correct command for Xilinx HLS (`vitis_hls` or `vivado_hls`) is detected by testing for availability of both commands, `vitis_hls` will take precedence over `vivado_hls`. 

Fixes #262

2021-04-20 17:40 UTC, wirthjohannes requested changes
Just the missing IP, the rest is fine

2021-04-20 17:40 UTC, wirthjohannes commented on toolflow/vivado/common/common_2020.2.tcl
> +dict set stdcomps   axi_cache        vlnv   "xilinx.com:ip:system_cache:5.0"
The IP `xxv_ethernet` is missing (see 2019.2; it's also missing in 2020.1). The version for 2020.2 is 3.3 (for 2020.1 3.2)

2021-04-20 20:20 UTC, wirthjohannes approved these changes

2021-04-20 20:20 UTC, merged